//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaFuncional.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public Libros()
        {
            this.Autores = new HashSet<Autores>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string n_paginas { get; set; }
        public Nullable<int> editorial_id { get; set; }
    
        public virtual Editoriales Editoriales { get; set; }
        public virtual ICollection<Autores> Autores { get; set; }
    }
}
